/**
 * strings constant across the application
 */

export const strings = {
    marketplace: 'Marketplace',
    downloadedModels: 'Downloaded Models',
    modelSelect: 'ModelSelect',
    blue: 'blue',
    black: 'black',
    center: 'center',
    row: 'row',
    green: 'green',
    iosCheckmarkIcon: 'checkmark-circle',
    downloadingModel: 'Downloading Model ',
    quote: '\'',
    threeDots: '...',
    labelDownloadStatus: 'Label Download Status: ',
    imageDownloadStatus: 'Image Download Status: ',
    modelInfoDownloadStatus: 'Model Info Download Status: ',
    modelFileDownloadStatus: 'Model File Download Status: ',
    white: 'white',
    bold: 'bold',
    flexEnd: 'flex-end',
    searchMarketPlace: 'SearchMarketPlace',
    searchModels: 'Search Models...',
    menuIcon: 'menu',
    updateQuery: 'UPDATE_QUERY',
    updateFinalQuery: 'UPDATE_FINAL_QUERY',
    updateRefreshComponent: 'UPDATE_REFRESH_COMPONENT',
    emptyString: '',
    granted: 'granted',
    permissionNeeded: 'Sorry, we need camera permissions to make this work!',
    modelInfo: 'modelInfo',
    labelsTxt: 'labels.txt',
    newline: '\n',
    pleaseSelectImage: 'Please first take an image or select an image from your gallery!',
    cameraIcon: 'camera-alt',
    takeImage: 'Take Image',
    photoIcon: 'photo-album',
    selectImage: 'Select Image',
    checkIcon: 'check',
    classifyImage: 'Classify Image',
    backArrowIcon: 'arrow-back',
    back: 'back',
    confidence: 'Confidence: ',
    percent: '%',
    gray: 'gray',
    hidden: 'hidden',
    borderColor: 'rgba(0,0,0,0.2)',
    eightyFivePercent: '85%',
    tealHex: '#01a699',
    periodSpace: '. ',
    label: 'label',
    openModel: 'Open Model',
    users: 'Users',
    slash: '/',
    up: 'up',
    deleteModel: 'Delete Model',
    upArrowIcon: 'arrow-upward',
    downArrowIcon: 'arrow-downward',
    leftParen: '(',
    space: ' ',
    rightParen: ')',
    reviews: ' Reviews',
    top1: 'top-1',
    top5: 'top-5',
    notSpecified: 'Not Specified\n',
    list: 'list',
    viewModelCategories: ' View Model Categories',
    close: ' Close',
    description: 'Decription',
    modelInformation: 'ModelInformation',
    top1Acc: 'Top-1 Accuracy: ',
    top5Acc: 'Top-5 Accuracy: ',
    numCats: 'Number of Categories: ',
    author: 'Author: ',
    searchModelCats: 'Search Model Categories',
    searchModelCatsCase: 'Search Model Categories Case Sensitively',
    arrowLeftIcon: 'keyboard-arrow-left',
    backCap: 'Back',
    hundredPercent: '100%',
    updateDownloadedModels: 'UPDATE_DOWNLOADED_MODELS',
    updateCloudModels: 'UPDATE_CLOUD_MODELS',
    delete: 'delete',
    textIcon: 'textsms',
    closeIcon: 'close',
    deleteReview: 'Delete Review',
    confirmDeleteReview: 'Are you sure you want to delete this review?',
    writeLongerReview: 'Please write a longer review!',
    writeReview: ' Write Review...',
    featuredModels: 'FeaturedModels',
    checkConnection: 'Please Check Network Connection and Refresh to View Featured Models',
    login: 'Login',
    enterEmailAndPass: 'Please enter email and password!',
    authError: 'Authentication Error: ',
    signup: 'SignUp',
    loading: 'Loading',
    signupText: 'Sign Up',
    loginText: 'Login',
    featured: 'Featured',
    search: 'Search',
    myModels: 'My Models',
    logout: 'Logout',
    appName: 'Image Classifier Marketplace',
    appVersion: 'v1.0',
    modelUse: 'ModelUse', 
    noDownloadedModels: 'You have not downloaded any models. Please download models from the marketplace! ',
    downloadError: 'There was an error downloading the model, most likely caused by a timeout from the server. Please try again.',
    noPersonalModels: 'You have not uploaded any models. ' + 
        'To upload your own models to the marketplace or for personal use, please go to http://soum.io',
    longerQuery: 'Please provide a longer search query!',
    noQueryMatch: 'No Models Match the Query',
    passNoMatch: 'Passwords do not match!',
    passShort: 'Password must be longer than 7 characters!',
    password: 'Password',
    rePassword: 'Re-type Password',

};